pipeline:
  build:
    image: node:latest
    commands:
      - sleep 10
      - npm install --silent
      - npm run --silent build || true
      - npm run test

  publish:
    image: plugins/docker
    repo: ecsdevops/aurora-core
    username: ecsdevops
    password: ${DOCKER_PASSWORD}
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}

services:
  redis:
    image: redis:alpine
  rabbit:
    image: rabbitmq:alpine
  gateway:
    image: ecsdevops/aurora-gateway
    entrypoint: /bin/bash
    command:
      - -c
      - sleep 5 && npm run ci
  manager:
    image: ecsdevops/aurora-manager
    entrypoint: /bin/bash
    command:
      - -c
      - sleep 8 && npm run ci
