pipeline:
  build:
    image: node:6.9
    commands:
        - npm install
        - npm run --silent build || true
        - npm run test

services:
  rabbit:
    image: rabbitmq:alpine
  manager:
    image: ecsdevops/aurora-manager
